

server:
  port: 8088
  servlet:
    context-path: /ddmo
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    #驱动
    driver-class-name: com.mysql.cj.jdbc.Driver
    #用户名
    username: root
    #密码
    password: zm813142
    #数据源地址
    url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
  rabbitmq:
    host: 43.254.2.249
    port: 5672
    username: admin
    password: admin
    virtual-host: /


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: flag  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

order-canal-bc-program:
  ip: 127.0.0.1
  port: 1111
  username: canal
  password: canal
  executeTime: 1566282900000
  filter: test.user
  destination: example4

order-test-user:
  ip: 127.0.0.1
  port: 11111
  username: canal
  password: canal
  executeTime: 1566282900000
  filter: test.user1
  destination: example4